In [3]:
import pandas as pd
import numpy as np

df1 = pd.read_excel('datavo2.xlsx',sheet_name='Table 1')
df2 = pd.read_excel('datavo2.xlsx',sheet_name='Table 2')
df3 = pd.read_excel('datavo2.xlsx',sheet_name='Figure 1-3')
df4 = pd.read_excel('datavo2.xlsx',sheet_name='Table 3-4')
df = pd.concat([df1,df2,df3,df4],axis = 1)
df = df.iloc[:, ~df.columns.duplicated()]
df.to_excel('datavott.xlsx')

In [5]:
g1 = np.array(df['Age'][df['GROUP'] == 1 ])
g2 = np.array(df['Age'][df['GROUP'] == 2 ])

In [7]:
from scipy.stats import ttest_ind,norm,f
import numpy as np
def ftest(s1,s2):
    '''F检验样本总体方差是否相等'''
    print("Null Hypothesis:var(s1)=var(s2)，α=0.05")
    F = np.var(s1)/np.var(s2)
    v1 = len(s1) - 1
    v2 = len(s2) - 1
    p_val = 1 - 2*abs(0.5-f.cdf(F,v1,v2))
    print(p_val)
    if p_val < 0.05:
        print("Reject the Null Hypothesis.")
        equal_var=False
    else:
        print("Accept the Null Hypothesis.")
        equal_var=True
    return equal_var
        
def ttest_ind_fun(s1,s2):
    '''t检验独立样本所代表的两个总体均值是否存在差异'''
    equal_var = ftest(s1,s2)
    print("Null Hypothesis:mean(s1)=mean(s2)，α=0.05")
    ttest,pval = ttest_ind(s1,s2,equal_var=equal_var)
    if pval < 0.05:
        print("Reject the Null Hypothesis.")
    else:
        print("Accept the Null Hypothesis.")
    return pval

np.random.seed(42)
s1 = norm.rvs(loc=1,scale=1.0,size=20)
s2 = norm.rvs(loc=1.5,scale=0.5,size=20)
s3 = norm.rvs(loc=1.5,scale=0.5,size=25)

#ttest_ind_fun(s1,s2)
t=ttest_ind_fun(g1,g2)

Null Hypothesis:var(s1)=var(s2)，α=0.05
0.38247604141155656
Accept the Null Hypothesis.
Null Hypothesis:mean(s1)=mean(s2)，α=0.05
Accept the Null Hypothesis.

In [8]:
df

,Number,Sex,Age,Height,Weight,BMI,VO2/Kg,HR,SBP,DBP,...,DBP-1,DBP-2,NO.,dLoad,dVE,dVT,dBF,dVD/VT,dVE/VCO2,dPETCO2
0,1,Male,21,182,65,19.623234,4.5,60,126,85,...,86,64,1,-3,-1.52,-0.12,0,-0.03,-1,1.0
1,2,Male,20,168,80,28.344671,3.8,79,104,52,...,55,51,2,-8,-1.16,-0.34,2,-0.05,0,-3.6
2,3,Female,29,160,52,20.312500,3.6,108,118,70,...,71,75,3,0,-3.15,0.04,-4,0.09,2,2.0
3,4,Male,25,180,75,23.148148,4.5,100,147,85,...,80,78,4,-12,-4.19,-0.01,-4,-0.03,-1,0.1
4,5,Male,25,170,59,20.415225,3.8,80,123,81,...,84,88,5,-4,1.39,0.35,-6,-0.11,-2,-0.1
5,6,Female,29,172,55,18.591130,4.3,98,126,75,...,90,81,6,-1,-0.92,0.08,-1,-0.09,-4,2.9
6,7,Female,30,158,47,18.827111,4.6,95,117,98,...,94,94,7,0,-1.77,0.01,-3,-0.11,-4,1.0
7,8,Male,25,172,85,28.731747,2.1,89,132,89,...,82,99,8,-1,3.03,0.39,-6,-0.14,-4,0.9
8,9,Female,26,160,57,22.265625,3.3,76,107,76,...,79,76,9,2,-4.99,-0.18,-3,-0.07,-5,2.8
9,10,Male,26,170,65,22.491349,4.0,87,134,83,...,64,77,10,1,-2.55,0.25,-6,-0.09,-4,3.6
10,11,Female,30,160,45,17.578125,4.2,80,88,64,...,70,71,11,0,-1.30,0.00,-2,0.08,5,-3.1
11,12,Female,27,160,60,23.437500,3.7,83,88,73,...,76,83,12,-16,-4.15,-0.04,-5,-0.06,-1,-1.1
12,13,Female,26,157,50,20.284799,4.5,116,105,80,...,85,79,13,-10,-3.65,-0.12,-2,-0.13,-3,-2.2
13,14,Female,27,163,47,17.689789,5.2,85,86,59,...,58,56,14,-30,-8.06,-0.07,-8,-0.01,0,-1.4
14,15,Male,26,170,65,22.491349,3.8,66,148,80,...,70,75,15,0,-3.44,0.01,-3,-0.11,-4,1.2
15,16,Male,28,172,66,22.309356,3.4,81,120,85,...,74,76,16,3,-3.36,0.01,-3,-0.17,-5,1.9
16,17,Female,21,158,60,24.034610,3.7,83,90,79,...,89,67,17,-12,-0.45,-0.03,1,-0.09,-3,1.0
17,18,Male,22,173,65,21.718066,4.2,98,122,72,...,75,73,18,-1,-1.19,0.14,-5,-0.08,-5,5.9
18,19,Female,20,160,75,29.296875,4.1,93,123,82,...,78,61,19,-27,-14.40,-0.35,-6,-0.02,-1,-0.2
19,20,Female,20,167,54,19.362473,4.6,84,96,77,...,66,67,20,-27,-7.97,-0.28,-3,-0.09,-3,-3.1
20,21,Male,19,180,59,18.209877,4.7,100,101,71,...,75,61,21,16,-0.14,0.11,-4,-0.07,-2,-0.2
21,22,Male,21,180,77,23.765432,5.1,79,110,87,...,88,84,22,-23,-5.83,0.04,-4,0.06,0,3.8
22,23,Female,21,170,50,17.301038,6.2,86,97,72,...,74,65,23,0,-0.20,0.07,-3,-0.10,-5,3.9
23,24,Female,20,163,49,18.442546,4.2,109,90,80,...,82,82,24,15,1.83,0.19,-2,0.12,0,6.9
24,25,Female,18,165,80,29.384757,3.2,90,113,83,...,76,76,25,-5,-8.19,0.11,-8,-0.11,-6,6.6
25,26,Female,21,154,47,19.817844,3.8,78,96,73,...,76,64,26,-10,-9.12,-0.18,-6,-0.08,-5,2.5
26,27,Male,21,180,68,20.987654,4.4,74,124,72,...,71,86,27,8,-2.82,0.02,-2,-0.02,-2,4.3
27,28,Male,21,182,62,18.717546,5.5,76,133,73,...,75,75,28,-20,-5.92,-0.05,-4,-0.06,-1,-1.4
28,29,Male,21,180,50,15.432099,3.6,103,133,89,...,89,81,29,-22,-3.84,-0.15,-1,-0.05,0,-3.5
29,30,Male,21,190,100,27.700831,3.6,80,118,92,...,89,71,30,4,-2.99,0.10,-3,-0.06,-3,2.0
30,31,Male,28,187,86,24.593211,3.1,101,114,74,...,74,84,31,0,-6.33,0.26,-6,-0.22,-4,-3.4
31,32,Female,20,165,50,18.365473,3.9,100,98,66,...,68,58,32,-30,-5.77,-0.36,0,0.01,2,-4.5
32,33,Male,21,182,70,21.132713,3.8,81,144,76,...,69,59,33,-20,-8.49,0.73,-9,-0.07,0,-1.0
33,34,Male,21,180,76,23.456790,3.9,85,132,64,...,60,58,34,-1,-4.02,0.58,-7,-0.12,-4,5.5

In [9]:
from scipy.stats import ttest_ind,norm,f
import numpy as np
def ftest(s1,s2):
    '''F检验样本总体方差是否相等'''
    #print("Null Hypothesis:var(s1)=var(s2)，α=0.05")
    F = np.var(s1)/np.var(s2)
    v1 = len(s1) - 1
    v2 = len(s2) - 1
    p_val = 1 - 2*abs(0.5-f.cdf(F,v1,v2))
    #print(p_val)
    if p_val < 0.05:
        #print("Reject the Null Hypothesis.")
        equal_var=False
    else:
        #print("Accept the Null Hypothesis.")
        equal_var=True
    return equal_var
        
def ttest_ind_fun(s1,s2):
    '''t检验独立样本所代表的两个总体均值是否存在差异'''
    equal_var = ftest(s1,s2)
    #print("Null Hypothesis:mean(s1)=mean(s2)，α=0.05")
    ttest,pval = ttest_ind(s1,s2,equal_var=equal_var)
    #if pval < 0.05:
        #print("Reject the Null Hypothesis.")
    #else:
        #print("Accept the Null Hypothesis.")
    return ttest,pval

def desc_ttest(df,var,group,v1,v2):
    g1 = np.array(df[var][df[group] == v1 ])
    g2 = np.array(df[var][df[group] == v2 ])
    t =  ttest_ind_fun(g1,g2)[0]
    p =  ttest_ind_fun(g1,g2)[1]
    dfn = df.groupby(group)
    a = pd.DataFrame(dfn[var].mean())
    b = pd.DataFrame(dfn[var].std())
    c = pd.DataFrame(dfn[var].count())
    d = pd.DataFrame({'t 值':[t],'P 值':[p]})
    d.index = [v1]
    e = pd.concat([c,a,b,d],axis =1)
    e = e.reset_index()
    e.sort_values(by='t 值',ascending = True,inplace = True)
    e.columns = ['组别','样本量','均值','标准差','t 值','P 值']
    e = e.replace(np.nan,' ')
    e.style.hide_index().format('{:.3f}',subset=['均值','标准差','t 值','P 值'])
    print("\n下为变量{}成组t检验结果:".format(var))
    return print(e)

#desc_ttest(df,'Age','GROUP',1,2)
#desc_ttest(df,'BMI','GROUP',1,2)

list0 = df.columns.to_list()
list1 = ['Number', 'Sex','GROUP']
list2 = [x for x in list0 if x not in list1]

for i in range(len(list2)):
    desc_ttest(df,list2[i],'GROUP',1,2)
for i in range(len(list2)):
    desc_ttest(df,list2[i],'Sex','Male','Female')

下为变量Age成组t检验结果:
   组别  样本量         均值       标准差       t 值       P 值
0   1   27  23.370370  3.398508 -0.222831  0.825083
1   2    7  23.714286  4.535574

下为变量Height成组t检验结果:
   组别  样本量          均值        标准差       t 值       P 值
0   1   27  170.259259   9.125588 -0.040474  0.967967
1   2    7  170.428571  12.567911

下为变量Weight成组t检验结果:
   组别  样本量         均值        标准差      t 值       P 值
0   1   27  63.740741  12.290060  0.39822  0.693113
1   2    7  61.428571  18.572894

下为变量BMI成组t检验结果:
   组别  样本量         均值       标准差       t 值      P 值
0   1   27  21.954235  3.754383  0.743941  0.46234
1   2    7  20.785308  3.480606

下为变量VO2/Kg成组t检验结果:
   组别  样本量        均值       标准差       t 值       P 值
0   1   27  4.107407  0.809048  0.332529  0.741659
1   2    7  4.000000  0.506623

下为变量HR成组t检验结果:
   组别  样本量         均值        标准差       t 值       P 值
0   1   27  87.259259  11.856814 -0.432204  0.668492
1   2    7  89.571429  15.468863

下为变量SBP成组t检验结果:
   组别  样本量          均值        标准差       t 值       P 值
0   1   27  116.925926  18.260773  1.388976  0.174432
1   2    7  106.571429  14.234432

下为变量DBP成组t检验结果:
   组别  样本量         均值       标准差      t 值       P 值
0   1   27  77.481481  9.807259  0.60559  0.549058
1   2    7  75.000000  9.000000

下为变量VO2@AT1成组t检验结果:
   组别  样本量         均值       标准差       t 值       P 值
0   1   27  14.407407  2.620030  1.267743  0.214037
1   2    7  13.014286  2.460643

下为变量VO2@AT2成组t检验结果:
   组别  样本量         均值       标准差       t 值       P 值
0   1   27  13.696296  3.410897  1.911921  0.067122
1   2    7  12.100000  1.365040

下为变量dVO2成组t检验结果:
   组别  样本量        均值       标准差       t 值       P 值
0   1   27 -0.711111  2.949880  0.170669  0.865559
1   2    7 -0.914286  2.075595

下为变量Load@AT1成组t检验结果:
   组别  样本量         均值        标准差       t 值       P 值
0   1   27  86.962963  21.066710  1.541821  0.132949
1   2    7  73.714286  16.306586

下为变量Load@AT2成组t检验结果:
   组别  样本量         均值        标准差       t 值       P 值
0   1   27  76.629630  25.211640 -0.351333  0.727641
1   2    7  80.142857  14.496305

下为变量dLOAD成组t检验结果:
   组别  样本量         均值        标准差       t 值       P 值
0   1   27 -10.333333  10.848609 -3.870752  0.000503
1   2    7   6.428571   6.778819

下为变量HR@AT1成组t检验结果:
   组别  样本量          均值        标准差       t 值       P 值
0   1   27  133.777778  14.399074 -0.036942  0.970761
1   2    7  134.000000  13.203535

下为变量HR@AT2成组t检验结果:
   组别  样本量          均值        标准差       t 值      P 值
0   1   27  127.925926  14.586416 -0.576232  0.56849
1   2    7  131.571429  16.267116

下为变量dHR成组t检验结果:
   组别  样本量        均值        标准差       t 值      P 值
0   1   27 -5.851852  10.290786 -0.822802  0.41671
1   2    7 -2.428571   7.367884

下为变量VE1成组t检验结果:
   组别  样本量         均值       标准差       t 值       P 值
0   1   27  21.529630  5.100722  1.134343  0.265077
1   2    7  19.135714  4.393119

下为变量VE2成组t检验结果:
   组别  样本量         均值       标准差       t 值       P 值
0   1   27  17.378889  4.955514  0.088426  0.930089
1   2    7  17.198571  4.106898

下为变量VT1成组t检验结果:
   组别  样本量        均值       标准差      t 值       P 值
0   1   27  1.060370  0.305331  0.47441  0.638429
1   2    7  0.997143  0.350177

下为变量VT2成组t检验结果:
   组别  样本量        均值       标准差       t 值       P 值
0   1   27  1.094815  0.430075  0.325348  0.747036
1   2    7  1.037143  0.360634

下为变量BF1成组t检验结果:
   组别  样本量         均值       标准差       t 值       P 值
0   1   27  21.222222  5.387545  0.418189  0.678602
1   2    7  20.285714  4.785892

下为变量BF2成组t检验结果:
   组别  样本量         均值       标准差       t 值       P 值
0   1   27  17.296296  5.304677 -0.060749  0.951937
1   2    7  17.428571  4.314979

下为变量VD/VT1成组t检验结果:
   组别  样本量        均值       标准差       t 值       P 值
0   1   27  0.207037  0.099337 -0.167601  0.867952
1   2    7  0.214286  0.112673

下为变量VD/VT2成组t检验结果:
   组别  样本量        均值       标准差       t 值       P 值
0   1   27  0.127407  0.096937 -2.266861  0.030293
1   2    7  0.224286  0.115882

下为变量VE/VCO2-1成组t检验结果:
   组别  样本量         均值       标准差      t 值       P 值
0   1   27  25.037037  2.724271 -0.72151  0.475835
1   2    7  25.857143  2.478479

下为变量VE/VCO2-2成组t检验结果:
   组别  样本量         均值       标准差       t 值       P 值
0   1   27  22.518519  2.517177 -2.270728  0.030032
1   2    7  25.142857  3.484660

下为变量PETCO2-1成组t检验结果:
   组别  样本量         均值       标准差       t 值       P 值
0   1   27  42.648148  3.664420  0.625543  0.536051
1   2    7  41.628571  4.535679

下为变量PETCO2-2成组t检验结果:
   组别  样本量         均值       标准差       t 值       P 值
0   1   27  43.251852  4.161303 -0.282636  0.779276
1   2    7  43.728571  3.050527

下为变量SBP-1成组t检验结果:
   组别  样本量          均值        标准差       t 值       P 值
0   1   27  139.407407  22.216174  1.372232  0.179534
1   2    7  127.000000  16.881943

下为变量SBP-2成组t检验结果:
   组别  样本量          均值        标准差       t 值       P 值
0   1   27  131.296296  22.655980  0.170508  0.865684
1   2    7  129.714286  18.108141

下为变量DBP-1成组t检验结果:
   组别  样本量         均值        标准差       t 值       P 值
0   1   27  76.111111  10.248202 -0.146192  0.884687
1   2    7  76.714286   7.040698

下为变量DBP-2成组t检验结果:
   组别  样本量         均值        标准差       t 值       P 值
0   1   27  73.074074  12.050937 -0.309127  0.759228
1   2    7  74.571429   8.141604

下为变量NO.成组t检验结果:
   组别  样本量         均值        标准差       t 值       P 值
0   1   27  17.407407  10.089062 -0.104872  0.917132
1   2    7  17.857143  10.205041

下为变量dLoad成组t检验结果:
   组别  样本量         均值        标准差       t 值       P 值
0   1   27 -10.333333  10.848609 -3.870752  0.000503
1   2    7   6.428571   6.778819

下为变量dVE成组t检验结果:
   组别  样本量        均值       标准差       t 值       P 值
0   1   27 -4.150741  3.743910 -1.485584  0.147175
1   2    7 -1.937143  2.254845

下为变量dVT成组t检验结果:
   组别  样本量        均值       标准差      t 值       P 值
0   1   27  0.034444  0.265059 -0.08245  0.934994
1   2    7  0.040000  0.116476

下为变量dBF成组t检验结果:
   组别  样本量        均值       标准差       t 值      P 值
0   1   27 -3.925926  2.854496 -1.654238  0.10837
1   2    7 -2.857143  0.899735

下为变量dVD/VT成组t检验结果:
   组别  样本量       均值       标准差       t 值       P 值
0   1   27 -0.07963  0.056737 -3.371761  0.001966
1   2    7  0.01000  0.083666

下为变量dVE/VCO2成组t检验结果:
   组别  样本量        均值       标准差      t 值      P 值
0   1   27 -2.518519  2.118969 -1.77317  0.08572
1   2    7 -0.714286  3.352327

下为变量dPETCO2成组t检验结果:
   组别  样本量        均值       标准差       t 值       P 值
0   1   27  0.603704  3.054440 -1.145923  0.260325
1   2    7  2.100000  3.181195

下为变量Age成组t检验结果:
       组别  样本量         均值       标准差      t 值       P 值
1    Male   18  22.888889  2.846854 -0.95111  0.348678
0  Female   16  24.062500  4.281258

下为变量Height成组t检验结果:
       组别  样本量          均值       标准差       t 值  P 值
1    Male   18  177.666667  6.343130  8.021362  0.0
0  Female   16  162.000000  4.830459

下为变量Weight成组t检验结果:
       组别  样本量         均值        标准差      t 值       P 值
1    Male   18  70.722222  11.900596  4.17819  0.000212
0  Female   16  54.875000   9.972462

下为变量BMI成组t检验结果:
       组别  样本量         均值       标准差       t 值       P 值
1    Male   18  22.403850  3.491919  1.166593  0.251996
0  Female   16  20.937012  3.840560

下为变量VO2/Kg成组t检验结果:
       组别  样本量        均值       标准差       t 值       P 值
1    Male   18  3.988889  0.763805 -0.789143  0.435836
0  Female   16  4.193750  0.746073

下为变量HR成组t检验结果:
       组别  样本量         均值        标准差       t 值       P 值
1    Male   18  84.388889  12.257717 -1.709139  0.097108
0  Female   16  91.500000  11.938732

下为变量SBP成组t检验结果:
       组别  样本量          均值        标准差       t 值       P 值
1    Male   18  125.833333  13.548388  5.062419  0.000017
0  Female   16  102.375000  13.415787

下为变量DBP成组t检验结果:
       组别  样本量         均值        标准差       t 值       P 值
1    Male   18  78.333333  10.116963  0.877807  0.386592
0  Female   16  75.437500   8.981230

下为变量VO2@AT1成组t检验结果:
       组别  样本量         均值       标准差       t 值       P 值
1    Male   18  14.044444  2.841545 -0.177449  0.860274
0  Female   16  14.206250  2.423625

下为变量VO2@AT2成组t检验结果:
       组别  样本量         均值       标准差       t 值       P 值
1    Male   18  13.866667  3.051518  0.978551  0.335142
0  Female   16  12.806250  3.266082

下为变量dVO2成组t检验结果:
       组别  样本量        均值       标准差       t 值       P 值
1    Male   18 -0.177778  2.628029  1.299793  0.202958
0  Female   16 -1.400000  2.854937

下为变量Load@AT1成组t检验结果:
       组别  样本量         均值        标准差       t 值       P 值
1    Male   18  96.611111  17.633988  4.766422  0.000039
0  Female   16  70.312500  14.060435

下为变量Load@AT2成组t检验结果:
       组别  样本量      均值        标准差       t 值       P 值
1    Male   18  92.000  17.214905  5.216547  0.000011
0  Female   16  60.875  17.534252

下为变量dLOAD成组t检验结果:
       组别  样本量        均值        标准差       t 值      P 值
1    Male   18 -4.611111  10.879765  1.159031  0.25502
0  Female   16 -9.437500  13.386405

下为变量HR@AT1成组t检验结果:
       组别  样本量          均值        标准差       t 值       P 值
1    Male   18  129.277778  13.046548 -2.116435  0.042179
0  Female   16  138.937500  13.547294

下为变量HR@AT2成组t检验结果:
       组别  样本量          均值        标准差       t 值      P 值
1    Male   18  125.555556  11.617544 -1.322064  0.19552
0  Female   16  132.187500  17.371313

下为变量dHR成组t检验结果:
       组别  样本量        均值        标准差       t 值       P 值
1    Male   18 -3.722222   8.005921  0.900174  0.374752
0  Female   16 -6.750000  11.480418

下为变量VE1成组t检验结果:
       组别  样本量         均值       标准差       t 值       P 值
1    Male   18  22.093889  5.077548  1.323095  0.195181
0  Female   16  19.847500  4.782432

下为变量VE2成组t检验结果:
       组别  样本量         均值       标准差       t 值       P 值
1    Male   18  19.128889  4.859671  2.515683  0.017095
0  Female   16  15.331250  3.796695

下为变量VT1成组t检验结果:
       组别  样本量        均值       标准差       t 值       P 值
1    Male   18  1.205556  0.305984  3.710944  0.000783
0  Female   16  0.869375  0.205409

下为变量VT2成组t检验结果:
       组别  样本量        均值       标准差       t 值       P 值
1    Male   18  1.334444  0.379415  5.075955  0.000023
0  Female   16  0.800000  0.222291

下为变量BF1成组t检验结果:
       组别  样本量         均值       标准差       t 值       P 值
1    Male   18  19.111111  5.356567 -2.440533  0.020382
0  Female   16  23.187500  4.230347

下为变量BF2成组t检验结果:
       组别  样本量         均值       标准差      t 值       P 值
1    Male   18  15.166667  4.617741 -2.92509  0.006283

0  Female   16  19.750000  4.494441

下为变量VD/VT1成组t检验结果:
       组别  样本量        均值       标准差       t 值       P 值
1    Male   18  0.182778  0.115290 -1.624274  0.114128
0  Female   16  0.237500  0.073802

下为变量VD/VT2成组t检验结果:
       组别  样本量        均值       标准差       t 值       P 值
1    Male   18  0.103889  0.108960 -2.754301  0.009619
0  Female   16  0.196250  0.082855

下为变量VE/VCO2-1成组t检验结果:
       组别  样本量         均值       标准差       t 值       P 值
1    Male   18  24.277778  2.824380 -2.292504  0.028598
0  Female   16  26.250000  2.081666

下为变量VE/VCO2-2成组t检验结果:
       组别  样本量         均值       标准差      t 值       P 值
1    Male   18  21.944444  2.484593 -2.57984  0.014681
0  Female   16  24.312500  2.868652

下为变量PETCO2-1成组t检验结果:
       组别  样本量     均值       标准差       t 值       P 值
1    Male   18  43.45  3.891053  1.689065  0.100929
0  Female   16  41.30  3.481379

下为变量PETCO2-2成组t检验结果:
       组别  样本量         均值       标准差      t 值       P 值
1    Male   18  44.394444  4.190672  1.69344  0.100086
0  Female   16  42.175000  3.337164

下为变量SBP-1成组t检验结果:
       组别  样本量          均值        标准差       t 值       P 值
1    Male   18  147.722222  19.447684  3.645775  0.000936
0  Female   16  124.625000  17.223530

下为变量SBP-2成组t检验结果:
       组别  样本量          均值        标准差       t 值       P 值
1    Male   18  140.388889  17.043677  3.016267  0.004983
0  Female   16  120.375000  21.595910

下为变量DBP-1成组t检验结果:
       组别  样本量         均值       标准差       t 值       P 值
1    Male   18  75.555556  9.871064 -0.433284  0.667715
0  Female   16  77.000000  9.507891

下为变量DBP-2成组t检验结果:
       组别  样本量         均值        标准差     t 值       P 值
1    Male   18  74.444444  12.200396  0.5773  0.567777
0  Female   16  72.187500  10.368020

下为变量NO.成组t检验结果:
       组别  样本量         均值        标准差       t 值      P 值
1    Male   18  18.555556  11.382247  0.649798  0.52046
0  Female   16  16.312500   8.276221

下为变量dLoad成组t检验结果:
       组别  样本量        均值        标准差       t 值      P 值
1    Male   18 -4.611111  10.879765  1.159031  0.25502
0  Female   16 -9.437500  13.386405

下为变量dVE成组t检验结果:
       组别  样本量       均值       标准差       t 值       P 值
1    Male   18 -2.96500  2.808886  1.274116  0.211798
0  Female   16 -4.51625  4.224310

下为变量dVT成组t检验结果:
       组别  样本量        均值       标准差       t 值       P 值
1    Male   18  0.128889  0.262788  2.600744  0.013965
0  Female   16 -0.069375  0.163563

下为变量dBF成组t检验结果:
       组别  样本量        均值       标准差       t 值       P 值
1    Male   18 -3.944444  2.645134 -0.561581  0.578314
0  Female   16 -3.437500  2.606882

下为变量dVD/VT成组t检验结果:
       组别  样本量        均值       标准差       t 值      P 值
1    Male   18 -0.078889  0.062204 -1.557241  0.12925
0  Female   16 -0.041250  0.078560

下为变量dVE/VCO2成组t检验结果:
       组别  样本量        均值       标准差      t 值       P 值
1    Male   18 -2.333333  1.814970 -0.44622  0.659513
0  Female   16 -1.937500  3.108456

下为变量dPETCO2成组t检验结果:
       组别  样本量        均值       标准差       t 值       P 值
1    Male   18  0.944444  2.925993  0.064348  0.949093
0  Female   16  0.875000  3.367987

In [13]:
from pyg2plot import Plot
import pandas as pd
import requests
import json


def mutual_sct(data,xvar,yvar):
    datat = data.to_json(orient='records')
    fund = json.loads(datat)
    scatter = Plot("Scatter")
    scatter.set_options(
    {
        'appendPadding': 30,
        'data': fund,
        'xField': xvar,
        'yField': yvar,
        'sizeField': 'dVO2',
        'colorField': 'Sex',
        'color': ['#ffd500','#82cab2'], #, ,'#ffd500','#82cab2', '#193442', '#d18768','#7e827a'
        'size': [4, 30],
        'shape': 'circle',
        'pointStyle':{'fillOpacity': 0.8,'stroke': '#bbb'},
        'xAxis':{'line':{'style':{'stroke': '#aaa'}},},
        'yAxis':{'line':{'style':{'stroke': '#aaa'}},},
        'quadrant':{
            'xBaseline': 0,
            'yBaseline': 0,
            #'labels': [
            #{'content': 'Male decrease,\nfemale increase'},
            #{'content': 'Female decrease,\nmale increase'},
            #{'content': 'Female & male decrease'},
            },#{'content': 'Female &\n male increase'}, ],
    })
    scatter.render('df' +'_' + xvar + '_'+ yvar + '散点图.html')#'df'+str(df.shape[0])+'行'+str(df.shape[1])+'列'+ xvar +yvar + '散点图.html')
    print('任务完成')
#mutual_sct(df,'dVEdVCO2','dVE'           )  
mutual_sct(df,'dLOAD','Age'           )   
#mutual_sct(df,'dLOAD', 'Height'       )   
#mutual_sct(df,'dLOAD', 'BMI'          )   
##mutual_sct(df,'dLOAD', 'VO2/Kg'       )   
#mutual_sct(df,'dLOAD', 'HR'           )   
#mutual_sct(df,'dLOAD', 'SBP'          )   
#mutual_sct(df,'dLOAD', 'DBP'          )   
#mutual_sct(df,'dLOAD', 'VO2@AT1'      )   
#mutual_sct(df,'dLOAD', 'VO2@AT2'      )   
#mutual_sct(df,'dLOAD', 'dVO2'         )   
#mutual_sct(df,'dLOAD', 'Load@AT1'     )   
#mutual_sct(df,'dLOAD', 'Load@AT2'     )   
#mutual_sct(df,'dLOAD', 'dLOAD'        )   
#mutual_sct(df,'dLOAD', 'HR@AT1'       )   
#mutual_sct(df,'dLOAD', 'HR@AT2'       )   
#mutual_sct(df,'dLOAD', 'dHR'          )   
#mutual_sct(df,'dLOAD', 'VE1'          )   
#mutual_sct(df,'dLOAD', 'VE2'          )   
#mutual_sct(df,'dLOAD', 'VT1'          )   
#mutual_sct(df,'dLOAD', 'VT2'          )   
#mutual_sct(df,'dLOAD', 'BF1'          )   
#mutual_sct(df,'dLOAD', 'BF2'          )   
#mutual_sct(df,'dLOAD', 'VD/VT1'       )   
#mutual_sct(df,'dLOAD', 'VD/VT2'       )   
#mutual_sct(df,'dLOAD', 'VE/VCO2-1'    )   
#mutual_sct(df,'dLOAD', 'VE/VCO2-2'    )   
#mutual_sct(df,'dLOAD', 'PETCO2-1'     )   
#mutual_sct(df,'dLOAD', 'PETCO2-2'     )   
#mutual_sct(df,'dLOAD', 'SBP-1'        )   
#mutual_sct(df,'dLOAD', 'SBP-2'        )   
#mutual_sct(df,'dLOAD', 'DBP-1'        )   
#mutual_sct(df,'dLOAD', 'DBP-2'        )   
#mutual_sct(df,'dLOAD', 'dVE'          )   
#mutual_sct(df,'dLOAD', 'dVT'          )   
#mutual_sct(df,'dLOAD', 'dBF'          )   
##mutual_sct(df,'dLOAD', 'dVD/VT'       )   
##mutual_sct(df,'dLOAD', 'dVE/VCO2'     )   
#mutual_sct(df,'dLOAD', 'dPETCO2'      )

任务完成

In [ ]:
list0 = df.columns.to_list()
list1 = ['Number', 'Sex','GROUP']
list2 = [x for x in list0 if x not in list1]
list2

In [ ]:
def ttest_ind_fun(s1,s2):
    '''t检验独立样本所代表的两个总体均值是否存在差异'''
    equal_var = ftest(s1,s2)
    #print("Null Hypothesis:mean(s1)=mean(s2)，α=0.05")
    ttest,pval = ttest_ind(s1,s2,equal_var=equal_var)
    #if pval < 0.05:
        #print("Reject the Null Hypothesis.")
    #else:
        #print("Accept the Null Hypothesis.")
    return ttest,pval
ttest_ind_fun(g1,g2)[0]

In [10]:
from scipy.stats import ttest_ind,norm,f
import numpy as np
g1 = np.array([265.4,271.5,284.6,291.3,254.8,275.9,281.7,268.6,264.1,273.2,270.8,260.5])
g2 = np.array([235.9,215.4,251.8,224.7,228.3,231.1,253.0,218.8,233.8,230.9,240.7,221.7,256.9,260.7,224.4])
g1mean = np.mean(g1)
g2mean = np.mean(g2)
g1std = np.std(g1)
g2std = np.std(g2)
t,p =  ttest_ind(g1,g2,equal_var = True)
print(g1mean,g2mean)
print(g1std,g2std)
print(t,p)

271.8666666666667 235.20666666666665
9.954423918818987 13.902731945756399
7.40186943904506 9.402290710761329e-08

In [10]:
dfn = df.groupby('GROUP')
a = pd.DataFrame(dfn.Age.mean())
b = pd.DataFrame(dfn.Age.std())
c = pd.DataFrame(dfn.Age.count())
d = pd.DataFrame({'t值':[t]})
d.index = d.index +1
e = pd.concat([c,a,b,d],axis =1)
e = e.reset_index()
e.columns = ['组别','样本量','均值','标准差','t值']
e.style.format('{:.2f}',subset=['均值','标准差']).hide_index()

In [11]:
e = pd.concat([c,a,b,d],axis =1)
e = e.reset_index()
e.columns = ['组别','样本量','均值','标准差','t值']
e.style.format('{:.2f}',subset=['均值','标准差']).hide_index()

In [6]:
col=df.iloc[:,2]
#取表中的第3列的所有值
arrs=col.values